/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class GradeManagementFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public GradeManagementFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGRADEID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSTUDENTID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSUBJECTID = new javax.swing.JTextField();
        btnENTERGRADE = new javax.swing.JButton();
        btnUPDATEGRADE = new javax.swing.JButton();
        btnDELETEGRADE = new javax.swing.JButton();
        btnBACKMAINMENU = new javax.swing.JButton();
        btnVIEWGRADE = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtGRADE = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("       GRADE MANAGEMENT ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Grade Id:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Student Id:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Subject Id:");

        btnENTERGRADE.setBackground(new java.awt.Color(255, 255, 255));
        btnENTERGRADE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnENTERGRADE.setText("Enter Grade");
        btnENTERGRADE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnENTERGRADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnENTERGRADEActionPerformed(evt);
            }
        });

        btnUPDATEGRADE.setBackground(new java.awt.Color(255, 255, 255));
        btnUPDATEGRADE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUPDATEGRADE.setText("Update Grade");
        btnUPDATEGRADE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUPDATEGRADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEGRADEActionPerformed(evt);
            }
        });

        btnDELETEGRADE.setBackground(new java.awt.Color(255, 255, 255));
        btnDELETEGRADE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDELETEGRADE.setText("Delete Grade");
        btnDELETEGRADE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDELETEGRADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEGRADEActionPerformed(evt);
            }
        });

        btnBACKMAINMENU.setBackground(new java.awt.Color(255, 255, 255));
        btnBACKMAINMENU.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBACKMAINMENU.setText("<--- Back");
        btnBACKMAINMENU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBACKMAINMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACKMAINMENUActionPerformed(evt);
            }
        });

        btnVIEWGRADE.setBackground(new java.awt.Color(255, 255, 255));
        btnVIEWGRADE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVIEWGRADE.setText("View Grade");
        btnVIEWGRADE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVIEWGRADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIEWGRADEActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Grade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtGRADEID, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtSTUDENTID, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtSUBJECTID, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnENTERGRADE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnUPDATEGRADE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnDELETEGRADE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnVIEWGRADE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtGRADE, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBACKMAINMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnBACKMAINMENU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGRADEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSTUDENTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSUBJECTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGRADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnENTERGRADE)
                    .addComponent(btnUPDATEGRADE)
                    .addComponent(btnDELETEGRADE)
                    .addComponent(btnVIEWGRADE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnENTERGRADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnENTERGRADEActionPerformed
        // TODO add your handling code here:
       //int gradeId = Integer.parseInt(txtGRADEID.getText());
        int studentId = Integer.parseInt(txtSTUDENTID.getText());
        int subjectId = Integer.parseInt(txtSUBJECTID.getText());
        String grade = txtGRADE.getText();
        
        
        try {
            Connection conn = DB.getConnection();
            String query = "INSERT INTO  grades (student_id, subject_id, grade) VALUES ( ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
//            stmt.setInt(1, gradeId);
            stmt.setInt(1, studentId);
            stmt.setInt(2, subjectId);
            stmt.setString(3, grade);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Grade Added Successfully");
        } catch (Exception ex) {
            
            System.out.println(ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error adding grade");
        }
    }//GEN-LAST:event_btnENTERGRADEActionPerformed

    private void btnUPDATEGRADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEGRADEActionPerformed
        // TODO add your handling code here:
        if (txtGRADEID.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Grade ID is required");
        return;
    }
        int gradeId = Integer.parseInt(txtGRADEID.getText());
        int studentId = Integer.parseInt(txtSTUDENTID.getText());
        int subjectId = Integer.parseInt(txtSUBJECTID.getText());
        String grade = txtGRADE.getText();
        
        try {
            Connection conn = DB.getConnection();
            String query = "UPDATE grades SET student_id = ?, subject_id = ?, grade = ? WHERE grade_id = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            
            stmt.setInt(1, studentId);
            stmt.setInt(2, subjectId);
            stmt.setString(3, grade);
            stmt.setInt(4, gradeId);
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Grade Updated Successfully");
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Grade updating Class");
        }
    }//GEN-LAST:event_btnUPDATEGRADEActionPerformed

    private void btnDELETEGRADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEGRADEActionPerformed
        // TODO add your handling code here:
        if (txtGRADEID.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Grade ID is required");
        return;
    }
        int gradeId = Integer.parseInt(txtGRADEID.getText());
        
        try {
            Connection conn = DB.getConnection();
            String query = "DELETE FROM grades WHERE grade_id = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setInt(1, gradeId);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Grade Deleted Successfully");
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Error deleting Grade");
        }
    }//GEN-LAST:event_btnDELETEGRADEActionPerformed

    private void btnVIEWGRADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIEWGRADEActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewGrade().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVIEWGRADEActionPerformed

    private void btnBACKMAINMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACKMAINMENUActionPerformed
        // TODO add your handling code here:
        DB obj = new DB();
        obj.returningToMainMenu();
        this.dispose();
    }//GEN-LAST:event_btnBACKMAINMENUActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBACKMAINMENU;
    private javax.swing.JButton btnDELETEGRADE;
    private javax.swing.JButton btnENTERGRADE;
    private javax.swing.JButton btnUPDATEGRADE;
    private javax.swing.JButton btnVIEWGRADE;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGRADE;
    private javax.swing.JTextField txtGRADEID;
    private javax.swing.JTextField txtSTUDENTID;
    private javax.swing.JTextField txtSUBJECTID;
    // End of variables declaration//GEN-END:variables
}
