/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ClassManagementFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public ClassManagementFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCLASSID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCLASSFIRSTN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTEACHERID = new javax.swing.JTextField();
        btnADDCLASS = new javax.swing.JButton();
        btnUPDATECLASS = new javax.swing.JButton();
        btnDELETECLASS = new javax.swing.JButton();
        btnBACKMAINMENU = new javax.swing.JButton();
        btnVIEWCLASS = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("       CLASS MANAGEMENT ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Class Id:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Class Name:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Teacher Id:");

        btnADDCLASS.setBackground(new java.awt.Color(255, 255, 255));
        btnADDCLASS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnADDCLASS.setText("Add Class");
        btnADDCLASS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnADDCLASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDCLASSActionPerformed(evt);
            }
        });

        btnUPDATECLASS.setBackground(new java.awt.Color(255, 255, 255));
        btnUPDATECLASS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUPDATECLASS.setText("Update Class");
        btnUPDATECLASS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUPDATECLASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATECLASSActionPerformed(evt);
            }
        });

        btnDELETECLASS.setBackground(new java.awt.Color(255, 255, 255));
        btnDELETECLASS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDELETECLASS.setText("Delete Class");
        btnDELETECLASS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDELETECLASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETECLASSActionPerformed(evt);
            }
        });

        btnBACKMAINMENU.setBackground(new java.awt.Color(255, 255, 255));
        btnBACKMAINMENU.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBACKMAINMENU.setText("<--- Back");
        btnBACKMAINMENU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBACKMAINMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACKMAINMENUActionPerformed(evt);
            }
        });

        btnVIEWCLASS.setBackground(new java.awt.Color(255, 255, 255));
        btnVIEWCLASS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVIEWCLASS.setText("View Class");
        btnVIEWCLASS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVIEWCLASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIEWCLASSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtCLASSID, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtCLASSFIRSTN, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(txtTEACHERID, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnADDCLASS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnUPDATECLASS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnDELETECLASS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnVIEWCLASS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBACKMAINMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnBACKMAINMENU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCLASSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCLASSFIRSTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTEACHERID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnADDCLASS)
                    .addComponent(btnUPDATECLASS)
                    .addComponent(btnDELETECLASS)
                    .addComponent(btnVIEWCLASS))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDCLASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDCLASSActionPerformed
        // TODO add your handling code here:
        //int classId = Integer.parseInt(txtCLASSID.getText());
        String className = txtCLASSFIRSTN.getText();
        String TeacherId = txtTEACHERID.getText();
        
        
        try {
            Connection conn = DB.getConnection();
            String query = "INSERT INTO classes (class_name, teacher_id) VALUES (?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
            //stmt.setInt(1, classId);
            stmt.setString(1, className);
            stmt.setString(2, TeacherId);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Class Added Successfully");
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Error adding class");
        }
    }//GEN-LAST:event_btnADDCLASSActionPerformed

    private void btnUPDATECLASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATECLASSActionPerformed
        // TODO add your handling code here:
        if (txtCLASSID.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Class ID is required");
        return;
    }
        int classId = Integer.parseInt(txtCLASSID.getText());
        String className = txtCLASSFIRSTN.getText();
        int teacherId = Integer.parseInt(txtTEACHERID.getText());
        
        try {
            Connection conn = DB.getConnection();
            String query = "UPDATE classes SET class_name = ?, teacher_id = ? WHERE class_id = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            
            stmt.setString(1, className);
            stmt.setInt(2, teacherId);
            stmt.setInt(3, classId);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Class Updated Successfully");
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Error updating Class");
        }
    }//GEN-LAST:event_btnUPDATECLASSActionPerformed

    private void btnDELETECLASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETECLASSActionPerformed
        // TODO add your handling code here:
        int classId = Integer.parseInt(txtCLASSID.getText());
        
        try {
            Connection conn = DB.getConnection();
            String query = "DELETE FROM classes WHERE class_id = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setInt(1, classId);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Class Deleted Successfully");
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Error deleting Class");
        }
    }//GEN-LAST:event_btnDELETECLASSActionPerformed

    private void btnVIEWCLASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIEWCLASSActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        new ViewClass().setVisible(true);
        
    }//GEN-LAST:event_btnVIEWCLASSActionPerformed

    private void btnBACKMAINMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACKMAINMENUActionPerformed
        // TODO add your handling code here:
        DB obj = new DB();
        obj.returningToMainMenu();
        this.dispose();
    }//GEN-LAST:event_btnBACKMAINMENUActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDCLASS;
    private javax.swing.JButton btnBACKMAINMENU;
    private javax.swing.JButton btnDELETECLASS;
    private javax.swing.JButton btnUPDATECLASS;
    private javax.swing.JButton btnVIEWCLASS;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCLASSFIRSTN;
    private javax.swing.JTextField txtCLASSID;
    private javax.swing.JTextField txtTEACHERID;
    // End of variables declaration//GEN-END:variables
}
